app = "bankysub-api"      # 👈 your app name from Fly.io
primary_region = "ams"    # Amsterdam, closest region

[build]
  builder = "heroku/builder:24"

[env]
  NODE_ENV = "production"
  PORT = "8080"           # 👈 make sure your app uses this

[[services]]
  internal_port = 8080    # 👈 match your app's port
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1m"
    restart_limit = 0
